title:              Leo Woolcock
email:              leo@leo-woolcock.co.uk
description:        Leo Woolcock's Development Journal and Portfolio
author:             Leo Woolcock
baseurl:            "/"
url:                "https://leo-woolcock.co.uk"

# Social Profiles
twitter_username:   leowoolcock
github_username:    L-Wo
facebook_username:  leowoolcock
instagram_username:  
linkedin_username: 

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           github
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
